# SonarQube Project Configuration
sonar.projectKey=wedding-shahnazia
sonar.projectName=wedding-shahnazia
sonar.projectVersion=1.0

# Source Code & Test File Mapping
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.jsx,src/**/*.test.js,src/**/*.spec.jsx,src/**/*.spec.js
sonar.exclusions=src/main.jsx,src/test/**,src/**/*.test.jsx,src/**/*.test.js,src/**/*.spec.jsx,src/**/*.spec.js

# Vitest Coverage LCOV Report Path
sonar.javascript.lcov.reportPaths=coverage/lcov.info
